auto_connect: true
default_connection: mysql
connections:
    mysql:
        host: localhost
        driver: mysql
        username: mysql_user
        password: j8dsf7sdnk3w89732df9dfn3
    sqlite:
        host: localhost
        driver: sqlite
        memory: true
        username: sqlite_user
        password: 9d732n32ffn3287dsfskfhk